# Generated by Django 4.2.1 on 2023-08-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cantidad')),
                ('date_start', models.DateField(verbose_name='Fecha Inicial')),
                ('date_end', models.DateField(verbose_name='Fecha Final')),
                ('disponible', models.BooleanField(verbose_name='Disponible')),
                ('cerrar', models.BooleanField(verbose_name='Cerrar')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plan', models.CharField(max_length=50, verbose_name='Id')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rooms', models.CharField(max_length=50, verbose_name='Id')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
    ]
