# Generated by Django 4.2.1 on 2023-05-29 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={},
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='checkout',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
