# Generated by Django 4.2.1 on 2023-05-29 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0002_alter_disponibilidad_options_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
