# Generated by Django 4.2.1 on 2023-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0003_plan_create_at_plan_update_at_rooms_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='checkin',
            field=models.DateField(auto_now=True, verbose_name='start'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='checkout',
            field=models.DateField(auto_now=True, verbose_name='end'),
        ),
    ]
