# Generated by Django 4.2.1 on 2023-05-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0004_disponibilidad_checkin_disponibilidad_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='checkin',
            field=models.DateField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='checkout',
            field=models.DateField(verbose_name='end'),
        ),
    ]
