# Generated by Django 4.2.1 on 2023-07-31 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_total_alter_booking_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tour',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Adultos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Adultos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Adultos'),
            preserve_default=False,
        ),
    ]
