# Generated by Django 4.2.1 on 2023-07-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_hotel_remove_booking_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.CharField(max_length=100, verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.CharField(max_length=100, verbose_name='Check-Out'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rooms',
            field=models.CharField(max_length=100, verbose_name='Habitaciones'),
        ),
    ]
